#!/usr/bin/env ruby
require 'sqlite3'

raise 'no/wrong details given' if ARGV.length != 4

email = ARGV[0]
server_in_host = ARGV[1]
server_in_port = ARGV[2].to_i
server_in_use_tls = (ARGV[3] == 'true') ? 1 : 0

db = SQLite3::Database.new 'data/database.db'
db.execute 'UPDATE accounts SET server_in_host=?,server_in_port=?,server_in_use_tls=? WHERE email=?', [server_in_host, server_in_port, server_in_use_tls, email]
