#!/usr/bin/env ruby
require 'sqlite3'
require 'bcrypt'

raise 'no/wrong details given' if ARGV.length != 1

username = ARGV[0]

db = SQLite3::Database.new 'data/database.db'
db.execute 'DELETE FROM users WHERE username=?', [username]
