#!/usr/bin/env ruby
require 'sqlite3'
require 'bcrypt'

raise 'no/wrong details given' if ARGV.length != 2

username = ARGV[0]
new_password = ARGV[1]
new_password = BCrypt::Password.create new_password

db = SQLite3::Database.new 'data/database.db'
db.execute 'UPDATE users SET password=? WHERE username=?', [new_password, username]
